### ISSUE TITLE
Handling people, roles, and user groups

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/data-service#25]
Following a discussion with @mattprintz @Sorrento110, it seems like it's a bad idea to put both users of TERArium and external author/maintainer info in the same table (currently `person` table where the column `is_registered` indicates if they are a user).
A few considerations need to be addressed
1. Do we want an `associations` table or should `person` be linked directly to asset?
2. How do we handle user permissions?

**Comment by mattprintz** [comment]
I think the key is that we don't want to conflate RBAC  access with external relationships.
I would suggest creating a separate `user` table, and the user table can have a FK to a person.
This way we can keep the external relationships, but don't have to worry about conflating the two concepts.

Also, we probably do want a `role` to help determine access control, but it also probably doesn't make sense to try to design RBAC rules or systems in a vacuum since it will, and must, be shared with the other systems and will probably cause conflicts.

I think that just adding the user table, with a user having a many-to-many relationship to projects is sufficient for the time being.

**Comment by YohannParis** [comment]
Indeed, the RBAC will be handled by a _User Management_ Service on TERArium HMI backend, that will work in tandem with _Keycloak_ our authentication system.
@dgauldie

**Comment by fivegrant** [comment]
TODO: Change `is_registered` to nullable FK `user_id` which links to _User Management Service_
